name: Build Binaries

on:
  push:
    branches:
      - actions
    tags:
      - 'v[0-9]+.*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

  build:
    name: Build Binaries
    needs: create_release
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade setuptools
          python3 -m pip install -r requirements.txt
          sudo python3 -m pip install pyinstaller

      - name: Build binaries
        run: |
          pyinstaller -F client.py
          pyinstaller -F server.py

      - name: Upload Client Binary (Windows)
        uses: actions/upload-release-asset@v1
        if: matrix.config.os == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: musik-client-${{ matrix.config.os }}.exe
          asset_path: ./dist/client.exe
          asset_content_type: application/octet-stream

      - name: Upload Client Binary
        uses: actions/upload-release-asset@v1
        if: matrix.config.os != 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: musik-client-${{ matrix.config.os }}
          asset_path: ./dist/client
          asset_content_type: application/octet-stream

      - name: Upload Server Binary (Windows)
        if: matrix.config.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: musik-server-${{ matrix.config.os }}.exe
          asset_path: ./dist/server.exe
          asset_content_type: application/octet-stream
      
      - name: Upload Server Binary
        if: matrix.config.os != 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: musik-server-${{ matrix.config.os }}
          asset_path: ./dist/server
          asset_content_type: application/octet-stream
